#!/usr/bin/env bash
# malbec-kernel: auto-provision kernel/lenovo/malbec header stub.
# Invoked automatically from lineage_malbec.mk during `lunch`/`breakfast`.
# Idempotent: only does work if the stub is missing or the tarball changed.
# Prints nothing on success-no-op; prints one line if it (re)creates the stub.

set -u
TOP="${1:-$(pwd)}"
KERNEL_DT="$TOP/device/lenovo/malbec-kernel"
TARBALL="$KERNEL_DT/kernel-headers/kernel-uapi-headers.tar.gz"
STUB="$TOP/kernel/lenovo/malbec"
MARKER="$STUB/.headers_hash"

[ -f "$TARBALL" ] || { echo "setup-kernel-headers: WARNING tarball missing at $TARBALL"; exit 0; }

NEW_HASH=$(sha256sum "$TARBALL" | awk '{print $1}')
OLD_HASH=""
[ -f "$MARKER" ] && OLD_HASH=$(cat "$MARKER" 2>/dev/null)

if [ -d "$STUB/usr" ] && [ -f "$STUB/Makefile" ] && [ "$NEW_HASH" = "$OLD_HASH" ]; then
  exit 0  # already set up and unchanged -- silent no-op, keeps lunch fast
fi

mkdir -p "$STUB"
rm -rf "$STUB/usr"
tar -xzf "$TARBALL" -C "$STUB"

cat > "$STUB/Makefile" <<'EOF'
# Auto-generated by malbec-kernel/setup-kernel-headers.sh -- DO NOT EDIT.
# Minimal stub satisfying `make headers_install` for vendor/lineage's
# generated_kernel_includes soong module. Not a real kernel build tree;
# no compile rules exist here on purpose.
VERSION = 6
PATCHLEVEL = 6
SUBLEVEL = 87
EXTRAVERSION =

O ?= .
INSTALL_HDR_PATH ?= $(O)/usr

.PHONY: headers_install
headers_install:
	@mkdir -p $(O)/usr
	@cp -r $(CURDIR)/usr/* $(O)/usr/ 2>/dev/null || true
EOF

echo "$NEW_HASH" > "$MARKER"
echo "setup-kernel-headers: provisioned kernel/lenovo/malbec from malbec-kernel tarball"
